name: secondbrain_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  google_generative_ai: ^0.4.7
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  objectbox_generator: ^4.3.0

flutter:
  uses-material-design: true
